apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-amigos-cc3s2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-amigos-cc3s2
  template:
    metadata:
      labels:
        app: hola-amigos-cc3s2
    spec:
      containers:
      - name: hola-amigos-cc3s2
        image: <your-image-name>
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: hola-amigos-cc3s2
spec:
  selector:
    app: hola-amigos-cc3s2
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
