elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
kibana:
  build: kibana
  ports:
    - "5601:5601"
  links:
   - elasticsearch
logstash:
  build: logstash
  links:
   - elasticsearch
user-registration:
  build: user-registration
  ports:
    - "8080:8080"
  volumes_from:
   - logstash


