carbon:
  build: carbon
  ports:
    - "2003:2003"
graphite-web:
  build: graphite-web
  ports:
    - "8082:80"
  volumes_from:
   - carbon
user-registration:
  build: user-registration
  ports:
    - "8083:8080"
  links:
   - carbon


