name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Build microservices with Maven
      run: cd microservice-demo && ./mvnw -B package --file pom.xml
    - name: Create Docker images 
      run: cd docker && docker-compose build